#!/bin/bash

update() {
	wget https://cdn.sklane.com/static/download/apk/Lane.apk -P /tmp
	adb install /tmp/Lane.apk
	rm /tmp/Lane.apk
}

if [ "$1" == "init" ]; then
	update
	adb install /usr/share/gnirehtet/gnirehtet.apk
	exit 0
fi
if [ "$1" == "update" ]; then
	update
	exit 0
fi

gnirehtet run &

export SCRCPY_ICON_PATH=/usr/share/lane/icon.png
scrcpy --new-display=1080x1920/350 --start-app=com.skiy.lane --window-title "Lane" --crop=1080:1800:0:0

pkill gnirehtet
